name: Build
on: { workflow_dispatch, push: { branches: [main] }, pull_request }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with: { extra_nix_config: experimental-features = nix-command flakes }
      - run: nix -vL --show-trace build .#homeConfigurations.default.activationPackage
